"""
This is the function by which we plot power verus elapsed time
Input is a data frame generated by test_info
"""
import matplotlib.pyplot as plt
from src.g_over_t.test_info import march_info, april_info, TestInfo

info = march_info


def plot_power(info: TestInfo) -> None:
    # Import these from `test_info.py` These are INSTANCES of the `TestInfo` class
    # Get the data (a DataFrame object) from info, which is a `TestInfo` instance
    data = info.data

    # Plot something
    fig, ax = plt.subplots()
    ax: plt.Axes
    ax.plot(data["elapsed"], data["power"])
    ax.set_xlabel("elapsed")
    ax.set_ylabel("power")

# Get the description from the `TestInfo` object, and use that as the title
    ax.set_title(info.description)

    plt.show()

plot_power(sept_info2)

